### ISSUE TITLE
403 on .mp4 URL

### ISSUE THREAD

**Issue by Valentin-Metz** [Shamdan17/PanoptoDownloader#1]
Hi there.
Valentin from TUM-University in Germany here.
I'm currently developing a downloader quite similar to yours.
If I try to access the .mp4-URL the server responds with a 403.

The browser is logged in and can play the video on the normal site.
Example URL: https://tum.cloud.panopto.eu/Panopto/Podcast/Social/f85e6074-2490-4309-b48c-acb7011ef5d9.mp4

**Comment by Shamdan17** [comment]
Hi Valentin!

Unfortunately I could not access TUM's panopto page since its behind a login page. I just tried it again with Koc's panopto and it seems to work fine.

I am not sure what's different with TUM's panopto, but you could try this:
Go to the player page where they video is playing, for us the url starts with something like:

`panopto.com/Panopto/Pages/Viewer`

Then try inspecting the page and looking for any link that ends with .mp4 . This is how I originally found out about it, before coming up with the simple url change to access the video. Can you check if its different on your end?

**Comment by Valentin-Metz** [comment]
This is a viewer-URL: https://tum.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=46645436-005e-4652-8519-acd3010bb31b
The page-source of the viewer-URL contains the video-URL three times: https://tum.cloud.panopto.eu/Panopto/Podcast/Social/46645436-005e-4652-8519-acd3010bb31b.mp4?mediaTargetType=videoPodcast
Accessing the video URL directly leads to a 403.

I have so far worked out a different approach plan:
If you enter a viewer-URL, open the "Network" tab of the dev-tools and look for a .m3u8 (playlist) file.
Youtube-dl and ffmpeg can handle those and are able to access the video through this file.
My current problem is accessing/extracting the playlist-file with selenium, as I do not know how to intercept the URL for the file.
![Network-Tab of Firefox](https://user-images.githubusercontent.com/31850924/114625323-563ecc80-9cb2-11eb-94cb-2bb84608077f.png)

**Comment by Valentin-Metz** [comment]
Closing this. Should anyone come upon this is the future, this is my solution: https://github.com/Valentin-Metz/tum_video_scraper/blob/master/src/tum_live.py

**Comment by Shamdan17** [comment]
@Valentin-Metz Thank you very much! I will adapt your solution and fix the script once I have time. I really appreciate you giving an update :)
